language: ruby
rvm:
- 2.6
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: u09FtNiHy+MCulBjYrPmmt+562tX1itkglcP/FXTXt7cDfQxLGtBxQks4O53cgh7INyLhnQhLLemV/QRmlTWQcogP37Dgx3aMru9cR18hmnZv8AmCcj/dHDC5wHyvZ9MeDEuBcmCgEdBbgHXuNRxkZt2ytnxxqfWa9HNdEjtkn9SsoBez3Tn07+RHKwQhN5KLZTou3lo3xZl76WcCqwSs3PqA5ESx5IJZnTS9CGiPJkgkRxTUQsiZAUxZt3fJNwK9iZmaBf0yGfZ28l4k3J5atsCoI1u5cwc68ZR6PNz7nmUwJdABY9Flc/w0ic9LeGJFYBx7Uc2zBQ2gxnHy+Brqh6iwhGYYWjgrUVUHjqI0RCHgEIVcg9dail7AD7ylXZEcN72OOTttjMZYqyT/2uAgd6SY2WZ3/CwjxxfiSudxtnT+5LTbtv1TmicZtMWLxEu40i8xYtafGpsQmf5lAD5LMV8fTlWxqSU0bOiKRHvM/r2R1Vk8gAHCfg2OKBFkDeC4iTW0C//9T9iaqvsG0/iVDlRbi18URagDSAYbnoS5F0qsyASA/SXsSNxwUo5tM2QikWk4flYMryY8Iwy9yRNjWxyBv+Yn3yQ3b+tj6gf42wIPBoruQe3Ee2VoV3FldRHgCDpuxOPUYvDv79NHo4mGi/HhC13brwrmz3fhivmMK0=
  - secure: wAoBPoVpBtF2krRBrL/3l4kCoC44qQNdipy71L/SoLPbYf3q3qE67VUxcgSz46DI2+vpGCD0dUTaqt6ujWVnokCJE+BrbINeN3R6xKeoxb0aTAQkRMllR05wHSy2cc8XPEKRsmHeMmwTCT6msJUIvJpgzmlF4GARbDW9Ai2kWbQhsg/c3Q58DDovK1ELrQNYEiSX4cFDD1/pSD7egTtU8y8YnPrL7tNQ4ooYnO9gSqRzCdKQserZSkqaMDJ+g5OsWU1K5aVpFuHJuZHIeZhn7ktUcdVnn1kRJapiGyT/2h88ujtI1SmOIfaQ1io2optXbK0QMc6lZxxSrEOnm1uGbtvPhZyWmW+e+9ecKCYlHZY2K5CSHkW27LHuDZA9ooqmI0OILshrQ//86emghHZc9PJ34rZgHHSZkBMkxIJdNnvHPZjty8NDRj+pV9nVaVm6G+frNiwPEHFjeTj+GiSyZ14GSBYGthhko21m1f5MyghygDEmaI/e15Oz22a2F5cCLdUHc41XbywZ5fTjvbmF8GRsSv3lkh8LkqInxM/NXnX2wI9bMVtPFhtu01qIDosaSyJSawMt1UuSd+TrI4aTEnLiSgaY9fheSl7U0aZi6Y2ujOIiSAihd/4rKw+ms5j+dX885C80wI0f4fnfiafRt0Lk66R54lhGLYZjClVboos=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
